[Web] Code increment #3
shreyner/go-shortener pull request #1
Opened 2022-05-30 19:55 UTC by shreyner

TODO

2022-06-01 09:01 UTC, ASPecherkin requested changes

2022-06-01 09:01 UTC, ASPecherkin commented on internal/core/shorted-url.go
> +package core
есть момент - в Go не принято такое название файлов через тире 
или  shortedurl или shorted_url , как больше нравится или как принято в репозитории/компании

2022-06-01 09:01 UTC, ASPecherkin commented on internal/handlers/shorted.go
> +	"fmt"
стилистический комментарий
в каждой компании или репозитории в Go есть принятый стиль сортировки пакетов в импортах
Чаще всего это

stdlib
пакеты приложения
внешние зависимости

Это можно получить путём установки и настройки в IDE комбинации https://golangci-lint.run/usage/install/ и goimports

2022-06-01 09:01 UTC, ASPecherkin commented on internal/handlers/shorted.go
> +func (sh *ShortedHandler) ShortedCreate(wr http.ResponseWriter, r *http.Request) {
из функций можно убрать упоминание Shorted - у тебя уже есть ресивер, который об этом говорит 
ShortedHander

2022-06-01 09:01 UTC, ASPecherkin commented on internal/storage/short-urls.go
> +	store map[string]core.ShortURL
этого нет в описании курса, но есть в использовании map в качестве хранилища
если будет конкуретная запись ( а она здесь возможна), то будет паника приложения
подробнее можно прочитать тут - https://medium.com/@luanrubensf/concurrent-map-access-in-go-a6a733c5ffd1

так же возможно и конкуретное чтение, поэтому лучше тут добавить RwMutex

2022-06-03 20:22 UTC, shreyner commented on internal/core/shorted-url.go
> +package core
Переименовал

2022-06-03 20:23 UTC, shreyner commented on internal/handlers/shorted.go
> +	"fmt"
Спасибо. Поставил линтер и отформатировал код с импортами

2022-06-03 20:23 UTC, shreyner commented on internal/handlers/shorted.go
> +func (sh *ShortedHandler) ShortedCreate(wr http.ResponseWriter, r *http.Request) {
Убрал из названий методов префикс

2022-06-03 20:25 UTC, shreyner commented on internal/storage/short-urls.go
> +	store map[string]core.ShortURL
Спасибо, это очень полезно и интересно.

Добавил RWMutex.

Вопрос: Могу ли Unlock вызывать через defer?

2022-06-09 09:44 UTC, ASPecherkin approved these changes
принимаю работу

2022-06-09 10:19 UTC, merged