[Web] Code increment 8
shreyner/go-shortener pull request #6
Opened 2022-06-21 20:02 UTC by shreyner

2022-06-22 22:03 UTC, ASPecherkin requested changes

2022-06-22 22:03 UTC, ASPecherkin commented on internal/storage/storage_file/storage_file.go
> +type FileStorage struct {
тут скорее всего и получилась у тебя путаница, как мне кажется по названиям

Репозиторий должен являться источником данных для какой-то бизнес сущности, а fileStore и memoryStore - это его реализации 

соответственно дальше у тебя два способа выделения интерфейса
сначала определить что нужно от репозитория - и такие функции сделать у имплементаций ( идеальный вариант)
или сделать имплементации и из них выделить общую часть в интерфейс репозитория

2022-06-22 22:03 UTC, ASPecherkin commented on internal/middlewares/gzlib-handler.go
> +func GzlibCompressHandler(next http.Handler) http.Handler {
смотри, если тут есть проблемы ( падают тесты в 8 инкременте ) я бы попробовал использовать стандартую middleware для gzip от chi - проверить упадёт ли он и если нет - сравнить код обработки 
если усё равно упадёт - значит есть проблема в приложении 
если совсем не пойдёт - напиши в чат группы, решим в чём проблема

2022-06-23 19:10 UTC, shreyner commented on internal/storage/storage_file/storage_file.go
> +type FileStorage struct {
Спасибо. Пересмотрел подход и исправил

2022-06-23 19:11 UTC, shreyner commented on internal/middlewares/gzlib-handler.go
> +func GzlibCompressHandler(next http.Handler) http.Handler {
Перепроверил код и ошибка оказалась в том что я использовал не flate за место gzip.
Поправил

2022-06-23 19:16 UTC, shreyner commented on internal/middlewares/gzlib-handler.go
> +func GzlibCompressHandler(next http.Handler) http.Handler {
Вернул обратно middleware

2022-06-25 22:13 UTC, ASPecherkin approved these changes

2022-06-26 09:41 UTC, merged